version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: server
      APP_PORT: 8080

  server:
    image: ghcr.io/mxpv/podsync:latest
    restart: on-failure
    ports:
      - "8082:8080"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/config.toml:/app/config.toml
    networks:
      default:
        ipv4_address: $APP_PODSYNC_IP
